# Dados de conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/forumhub
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
api.security.token.secret=${JWT_SECRET:12345678}

logging.level.org.springframework.security=DEBUG